"""add_price

Revision ID: 06463ae1af1e
Revises: fb8ce6ce7c6b
Create Date: 2021-11-28 22:42:53.653144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "06463ae1af1e"
down_revision = "fb8ce6ce7c6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "steam_app", sa.Column("initial_price", sa.Integer(), nullable=True)
    )
    op.add_column(
        "steam_app", sa.Column("current_price", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("steam_app", "current_price")
    op.drop_column("steam_app", "initial_price")
    # ### end Alembic commands ###
