"""correct_nullability

Revision ID: 678f3de91b2a
Revises: 06463ae1af1e
Create Date: 2023-11-23 12:33:45.400253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "678f3de91b2a"
down_revision = "06463ae1af1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("appid_error", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("categorysteamapplink", schema=None) as batch_op:
        batch_op.alter_column("category_pk", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "steam_app_pk", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("genre", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("genresteammapplink", schema=None) as batch_op:
        batch_op.alter_column("genre_pk", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "steam_app_pk", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("steam_app", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "achievements_total", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("steam_app", schema=None) as batch_op:
        batch_op.alter_column(
            "achievements_total", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("genresteammapplink", schema=None) as batch_op:
        batch_op.alter_column("steam_app_pk", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("genre_pk", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("genre", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("categorysteamapplink", schema=None) as batch_op:
        batch_op.alter_column("steam_app_pk", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("category_pk", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("appid_error", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.alter_column(
            "pk", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    # ### end Alembic commands ###
