"""init

Revision ID: fb8ce6ce7c6b
Revises: 
Create Date: 2021-11-27 16:52:18.035895

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "fb8ce6ce7c6b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appid_error",
        sa.Column("pk", sa.Integer(), nullable=True),
        sa.Column("appid", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("appid"),
    )
    op.create_table(
        "category",
        sa.Column("pk", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "genre",
        sa.Column("pk", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "steam_app",
        sa.Column("pk", sa.Integer(), nullable=True),
        sa.Column("appid", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "controller_support",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("metacritic_score", sa.Integer(), nullable=True),
        sa.Column(
            "metacritic_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("recommendations", sa.Integer(), nullable=True),
        sa.Column("achievements_total", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_index(
        op.f("ix_steam_app_appid"), "steam_app", ["appid"], unique=True
    )
    op.create_index(
        op.f("ix_steam_app_name"), "steam_app", ["name"], unique=False
    )
    op.create_table(
        "achievement",
        sa.Column("pk", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("percent", sa.Float(), nullable=False),
        sa.Column("steam_app_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["steam_app_pk"],
            ["steam_app.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "categorysteamapplink",
        sa.Column("category_pk", sa.Integer(), nullable=True),
        sa.Column("steam_app_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_pk"],
            ["category.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["steam_app_pk"],
            ["steam_app.pk"],
        ),
        sa.PrimaryKeyConstraint("category_pk", "steam_app_pk"),
    )
    op.create_table(
        "genresteammapplink",
        sa.Column("genre_pk", sa.Integer(), nullable=True),
        sa.Column("steam_app_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genre_pk"],
            ["genre.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["steam_app_pk"],
            ["steam_app.pk"],
        ),
        sa.PrimaryKeyConstraint("genre_pk", "steam_app_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("genresteammapplink")
    op.drop_table("categorysteamapplink")
    op.drop_table("achievement")
    op.drop_index(op.f("ix_steam_app_name"), table_name="steam_app")
    op.drop_index(op.f("ix_steam_app_appid"), table_name="steam_app")
    op.drop_table("steam_app")
    op.drop_table("genre")
    op.drop_table("category")
    op.drop_table("appid_error")
    # ### end Alembic commands ###
