name: Run steam-to-sqlite

on:
  schedule:
    - cron: "19 * * * *" # every hour

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install library
        run: |
          poetry env use "3.10"
          poetry install --no-interaction

      - name: run the script
        run: |
          wget -qO database.db https://www.dropbox.com/s/i47qt3chrp9lr9e/database.db?dl=1
          poetry run alembic upgrade head
          poetry run python steam2sqlite/main.py --limit 45
        shell: bash

      - name: upload to dropbox
        run: |
          poetry run scripts/uploader.py database.db /database.db
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        shell: bash

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: database.db
          path: database.db

      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: |-
          poetry run datasette publish vercel database.db \
            --token $NOW_TOKEN \
            --install datasette-graphql --install datasette-vega \
            --project steam-to-sqlite \
            --metadata datasette-data/metadata.json
