name: Run steam-to-sqlite

on:
  schedule:
    - cron: "0 * * * *" # every hour

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # load cached venv if cache exists
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      - name: run the script
        run: |
          source .venv/bin/activate
          wget -qO database.db https://www.dropbox.com/s/i47qt3chrp9lr9e/database.db?dl=1
          python steam2sqlite/main.py --limit 45
        shell: bash

      - name: upload to dropbox
        run: |
          source .venv/bin/activate
          python scripts/uploader.py database.db /database.db
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        shell: bash

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: database.db
          path: database.db

      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: |-
          source .venv/bin/activate
          datasette publish vercel database.db \
            --token $NOW_TOKEN \
            --install datasette-graphql \
            --project steam-to-sqlite \
            --metadata datasette-data/metadata.json
