name: Test steam-to-sqlite

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install ".[dev]"

      - name: test
        run: |
          alembic upgrade head
          pytest --cov=steam2sqlite --cov-report=xml
        env:
          APPIDS_FILE: test_data/app_list_limited.json

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
