name: Test steam-to-sqlite

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: test
        run: |
          poetry run alembic upgrade head
          poetry run pytest --cov=steam2sqlite --cov-report=xml
        env:
          APPIDS_FILE: test_data/app_list_limited.json

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
